def columns2NLP(raw_data):
    raw_data = raw_data.replace("COUNT", "统计个数")
    raw_data = raw_data.replace("MEAN", "均值")
    raw_data = raw_data.replace("SUM", "求和")
    raw_data = raw_data.replace("MIN", "最小值")
    raw_data = raw_data.replace("MAX", "最大值")
    raw_data = raw_data.replace("STD", "标准差")
    raw_data = raw_data.replace("MODE", "众数")
    raw_data = raw_data.replace("MEDIAN", "中位数")
    raw_data = raw_data.replace("AVG_TIME_BETWEEN", "间隔时间")
    raw_data = raw_data.replace("TIME_SINCE_LAST", "距离最后时间")
    raw_data = raw_data.replace("TIME_SINCE_FIRST", "距离最初时间")
    raw_data = raw_data.replace("NUM_UNIQUE", "唯一值个数")
    raw_data = raw_data.replace("PERCENT_TRUE", "真值百分比")
    raw_data = raw_data.replace("ALL", "是否全为真")
    raw_data = raw_data.replace("ANY", "是否存在真")
    raw_data = raw_data.replace("LAST", "最后一个值")
    raw_data = raw_data.replace("SKEW", "正态偏离")
    raw_data = raw_data.replace("TREND", "变化趋势")

    raw_data = raw_data.replace("IS_IN", "是否存在值")
    raw_data = raw_data.replace("AND", "逻辑且")
    raw_data = raw_data.replace("OR", "逻辑或")
    raw_data = raw_data.replace("NOT", "逻辑否")
    raw_data = raw_data.replace("ABSOLUTE", "绝对值")
    raw_data = raw_data.replace("PERCENTILE", "百分位数")
    raw_data = raw_data.replace("TIME_SINCE", "距指定日期时间")
    raw_data = raw_data.replace("SECOND", "秒")
    raw_data = raw_data.replace("MINUTE", "分钟")
    raw_data = raw_data.replace("WEEKDAY", "当周第几天")
    raw_data = raw_data.replace("IS_WEEKEND", "是否周末")
    raw_data = raw_data.replace("HOUR", "小时")
    raw_data = raw_data.replace("DAY", "当月第几天")
    raw_data = raw_data.replace("WEEK", "当年第几周")
    raw_data = raw_data.replace("MONTH", "月")
    raw_data = raw_data.replace("YEAR", "年")
    raw_data = raw_data.replace("DIFF", "和上个值之差")
    raw_data = raw_data.replace("TIME_SINCE_PREVIOUS", "距上个时间戳时间")
    raw_data = raw_data.replace("NUM_CHARACTERS", "字符个数")
    raw_data = raw_data.replace("NUM_WORDS", "单词个数")
    raw_data = raw_data.replace("LATITUDE", "纬度")
    raw_data = raw_data.replace("LONGITUDE", "经度")
    raw_data = raw_data.replace("HAVERSINE", "半正矢距离")
    return raw_data


if __name__ == '__main__':
    print(columns2NLP("COUNT(transactions)"))
